[project]
name = "tucil2-steganography"
version = "1.0.0"
description = "Tucil II IF4020 - MP3 multiple-LSB steganography"
requires-python = ">=3.10"
dependencies = ["numpy", "pydub"]

[project.scripts]
tucil2-stego = "gui.app:main"