[project]
name = "stega-gui-mp3"
version = "0.1.0"
description = "Steganography (IF4020 Tucil II)"
requires-python = ">=3.10"
dependencies = ["numpy", "pydub"]

[project.scripts]
stega-gui = "app.main:main"